// generated by stringer -type=Vehicle; DO NOT EDIT

package reg

import "fmt"

const (
	_Vehicle_name_0 = "UnknownTaxi"
	_Vehicle_name_1 = "FHV"
	_Vehicle_name_2 = "Other"
)

var (
	_Vehicle_index_0 = [...]uint8{0, 7, 11}
	_Vehicle_index_1 = [...]uint8{0, 3}
	_Vehicle_index_2 = [...]uint8{0, 5}
)

func (i Vehicle) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _Vehicle_name_0[_Vehicle_index_0[i]:_Vehicle_index_0[i+1]]
	case i == 4:
		return _Vehicle_name_1
	case i == 8:
		return _Vehicle_name_2
	default:
		return fmt.Sprintf("Vehicle(%d)", i)
	}
}
